[project]
name = "segdino"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow",
    "numpy",
    "opencv-python-headless",
    "tqdm",
    "torch",
    "torchvision",
    "transformers",
    "python-dotenv",
    "huggingface-hub",
]
